[package]
name = "carapace-shortcutter"
version = "0.1.0"
edition = "2024"
description = "A command-line tool that makes aliases of shell commands and lua scripts"
license = "MIT"
repository = "https://github.com/charlesjchai/carapace-shortcutter"

[[bin]]
name = "pacecut"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
serde_json = "1.0"
directories = "6.0"
