mod args;

use anyhow::{Context, Ok, Result};
use args::CarapaceArgs;
use clap::Parser;
use serde_json::Value;
use std::env;
use std::fs::{self, File};
use std::io::{self, BufReader, BufWriter, Write};
use std::os::unix::fs::OpenOptionsExt;
use std::path::{self, Path, PathBuf};
#[cfg(not(unix))]
compile_error!("MICROSLOP LOVER AHHHHHHHHHH");

fn main() -> Result<()> {
    let json_path = PathBuf::from("resources/settings.json");
    let aliases_path = PathBuf::from("resources/aliases");
    let json_file = File::options()
        .read(true)
        .write(true)
        .create(true)
        .open(json_path.to_str().unwrap())
        .context(area_err!("Could not open settings.json"))?;
    let mut aliases_file = File::options()
        .read(true)
        .write(true)
        .create(true)
        .mode(0o755)
        .open(aliases_path.to_str().unwrap())
        .context(area_err!("Could not open `aliases` file"))?;
    // writeln!(aliases_file, "ls")?;
    let reader = BufReader::new(&json_file);

    // Either creates a mutable copy of settings.json or initializes an empty one
    let mut json_val = if json_file.metadata()?.len() == 0 {
        Value::Object(serde_json::Map::new())
    } else {
        serde_json::from_reader(reader).context(area_err!("Invalid syntax"))?
    };
    let settings_json = json_val
        .as_object_mut()
        .context(area_err!("Not an object"))?;

    let rc_path: PathBuf;
    let mut stdin_buf = String::new();

    // Convert the home directory into a Cow and back into a String
    let home_dir_string: String = home::home_dir().unwrap().to_string_lossy().into_owned();

    // Asks for the shell's rc file if it isn't found
    if settings_json.contains_key("rc_file") {
        rc_path = PathBuf::from(
            settings_json["rc_file"]
                .as_str()
                .context(area_err!("Error reading JSON"))?,
        );
    } else {
        print!(
            "The shell's rc file was not specified. \n\
        Please provide the RELATIVE path to it (.zshrc, .bashrc), \
        or type \"auto\" to find it automatically.\n\n\
        ~/"
        );
        loop {
            io::stdout().flush()?;
            io::stdin()
                .read_line(&mut stdin_buf)
                .context(area_err!("Failed to read rc file"))?;
            if stdin_buf.trim() == "auto" {
                stdin_buf = find_shell_rc(&home_dir_string);
                if stdin_buf.is_empty() {
                    print!(
                        "A shell rc file could not be found. Please try again\n\
                    ~/"
                    );
                    continue;
                }
            }
            break;
        }
        rc_path = PathBuf::from(format!("{home_dir_string}/{}", stdin_buf.trim()));
        settings_json.insert(
            "rc_file".to_owned(),
            Value::String(rc_path.to_string_lossy().into_owned()),
        );
    }
    dbg!(&settings_json);
    dbg!(rc_path.to_str().unwrap());

    // Find if shell rc contains `aliases`
    let aliases_temp: PathBuf = path::absolute(&aliases_path)?;
    let aliases_path_str = aliases_temp.to_str().unwrap();
    // let aliases_reg = Regex::new(&format!(r"\\n(\\s*\\{})", aliases_path_str))?;
    let mut rc_file = File::options()
        .append(true)
        .create(true)
        .open(&rc_path)
        .context(area_err!(
            "Shell rc file could not be opened, try running `pacecut reconfig`"
        ))?;
    let rc_contents = fs::read_to_string(&rc_path).unwrap();
    if !rc_contents.contains(aliases_path_str) {
        println!("`aliases` file not found in shell rc, inserting...");
        writeln!(
            rc_file,
            ". {} # Generated by carapace-shortcutter",
            path::absolute(&aliases_path)?.to_str().unwrap()
        )?;
        json_save(&json_path, &json_val);
        dbg!(path::absolute(&aliases_path)?.to_str().unwrap());
    }

    let args = CarapaceArgs::parse();

    json_save(&json_path, &json_val);
    Ok(())
}

/// Formats an error message with its location (file, line and column)
/// Only use with `anyhow::context`
macro_rules! area_err {
    ($a:expr) => {
        format!("Error \"{}\" at {}:{}:{}", $a, file!(), line!(), column!())
    };
}
pub(crate) use area_err;

/// Finds the shell's rc depending on the current shell
fn find_shell_rc(home_string: &str) -> String {
    let current_shell =
        env::var("SHELL").expect("$SHELL not found. Something is seriously wrong with your shell.");
    dbg!(home_string);
    dbg!(&current_shell);
    // The path relative to the home directory (.bashrc, .zshrc)
    let mut relative_rc_path = String::new();

    if current_shell.contains("/bash") {
        relative_rc_path = ".bashrc".to_owned();
    } else if current_shell.contains("/sh") {
        relative_rc_path = ".profile".to_owned();
    } else if current_shell.contains("/zsh") {
        const ZSH_RC_PRIORITY: [&str; 3] = [".zshrc", ".config/.zshrc", ".config/zsh/.zshrc"];

        // Loop through the priority list, stopping once an existing file has been found
        for zsh_relative_rc_path in ZSH_RC_PRIORITY {
            let zsh_absolute_rc_path = format!("{home_string}/{zsh_relative_rc_path}");
            dbg!(&zsh_absolute_rc_path);
            if fs::exists(Path::new(&zsh_absolute_rc_path)).unwrap_or(false) {
                relative_rc_path = zsh_relative_rc_path.to_owned();
                break;
            }
        }
    }

    if relative_rc_path.is_empty() {
        return String::new();
    }
    println!("Choosing {home_string}/{relative_rc_path} as shell rc...");
    format!("{relative_rc_path}")
}

fn json_save(path: &Path, value: &Value) {
    // Truncate the file and quit
    let file = File::create(path).unwrap();
    let mut writer = BufWriter::new(file);
    serde_json::to_writer_pretty(&mut writer, value).expect("Could not read Value");
    writer.flush().unwrap();
}
